
dataset: image-folder
dataset_args: 
    root_path: ./dataset/test

example_dataset_args:
    root_path: ./dataset/example/slitlamp

load : ./outputs/convnext_base/meta_image-folder-5shot-meta-baseline_slitlamp/epoch-3.pth

#few shot test param
n_shots: [10]
n_way: 3
n_query: 15
test_batches: 100
#QerySet Num
ep_per_batch: 4
example_shot: 20

nearest_point: False

